name: Fast-Trips
channels:
  - anaconda/label/archive
  - conda-forge/label/cf201901
  - conda-forge/label/cf202003
  - conda-forge/label/archive
  - conda-forge
  - defaults
dependencies:
  - python=2.7
  - bokeh=0.12.4=py27_0
  - free::datashader=0.4.0
  - notebook=4.3.1
  - numpy=1.11.3
  - pandas=0.19.2
  - pyproj=1.9.5.1
  - seaborn
  - pip=19.3.1
  - pip:
    - folium==0.2.1
    - transitfeed==1.2.14
    - fasttrips==1.0a14
