name: Fast-Trips-Tutorial-AppCon2017
channels:
  - anaconda/label/archive
  - conda-forge/label/cf201901
  - conda-forge/label/cf202003
  - conda-forge/label/archive
  - conda-forge
  - defaults
dependencies:
  - python=2.7.13
  - bokeh::bokeh=0.12.4
  - free::datashader=0.4.0
  - notebook=4.3.1
  - numpy=1.11.3
  - pandas=0.19.2
  - pyproj=1.9.5.1
  - seaborn
  - pip:
    - folium==0.2.1
    - transitfeed==1.2.14
    - fasttrips
